// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: service_pc.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pc *PC `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
}

func (x *CreatePCRequest) Reset() {
	*x = CreatePCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePCRequest) ProtoMessage() {}

func (x *CreatePCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePCRequest.ProtoReflect.Descriptor instead.
func (*CreatePCRequest) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePCRequest) GetPc() *PC {
	if x != nil {
		return x.Pc
	}
	return nil
}

type CreatePCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePCResponse) Reset() {
	*x = CreatePCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePCResponse) ProtoMessage() {}

func (x *CreatePCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePCResponse.ProtoReflect.Descriptor instead.
func (*CreatePCResponse) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePCResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchPCRequest) Reset() {
	*x = SearchPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPCRequest) ProtoMessage() {}

func (x *SearchPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPCRequest.ProtoReflect.Descriptor instead.
func (*SearchPCRequest) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPCRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pc *PC `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
}

func (x *SearchPCResponse) Reset() {
	*x = SearchPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPCResponse) ProtoMessage() {}

func (x *SearchPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPCResponse.ProtoReflect.Descriptor instead.
func (*SearchPCResponse) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPCResponse) GetPc() *PC {
	if x != nil {
		return x.Pc
	}
	return nil
}

var File_service_pc_proto protoreflect.FileDescriptor

var file_service_pc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x02, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x50, 0x43, 0x52, 0x02, 0x70, 0x63, 0x22,
	0x22, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x2e,
	0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x02, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x50, 0x43, 0x52, 0x02, 0x70, 0x63, 0x32, 0xbf,
	0x01, 0x0a, 0x09, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x08,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x12, 0x17, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x70, 0x63, 0x3a, 0x01, 0x2a, 0x12, 0x59, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x43, 0x12, 0x17, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x63, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x63, 0x3a, 0x01, 0x2a, 0x30, 0x01,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_pc_proto_rawDescOnce sync.Once
	file_service_pc_proto_rawDescData = file_service_pc_proto_rawDesc
)

func file_service_pc_proto_rawDescGZIP() []byte {
	file_service_pc_proto_rawDescOnce.Do(func() {
		file_service_pc_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_pc_proto_rawDescData)
	})
	return file_service_pc_proto_rawDescData
}

var file_service_pc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_pc_proto_goTypes = []interface{}{
	(*CreatePCRequest)(nil),  // 0: pcbook.CreatePCRequest
	(*CreatePCResponse)(nil), // 1: pcbook.CreatePCResponse
	(*SearchPCRequest)(nil),  // 2: pcbook.SearchPCRequest
	(*SearchPCResponse)(nil), // 3: pcbook.SearchPCResponse
	(*PC)(nil),               // 4: pcbook.PC
	(*Filter)(nil),           // 5: pcbook.Filter
}
var file_service_pc_proto_depIdxs = []int32{
	4, // 0: pcbook.CreatePCRequest.pc:type_name -> pcbook.PC
	5, // 1: pcbook.SearchPCRequest.filter:type_name -> pcbook.Filter
	4, // 2: pcbook.SearchPCResponse.pc:type_name -> pcbook.PC
	0, // 3: pcbook.PCService.CreatePC:input_type -> pcbook.CreatePCRequest
	2, // 4: pcbook.PCService.SearchPC:input_type -> pcbook.SearchPCRequest
	1, // 5: pcbook.PCService.CreatePC:output_type -> pcbook.CreatePCResponse
	3, // 6: pcbook.PCService.SearchPC:output_type -> pcbook.SearchPCResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_pc_proto_init() }
func file_service_pc_proto_init() {
	if File_service_pc_proto != nil {
		return
	}
	file_pc_message_proto_init()
	file_filter_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_pc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_pc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_pc_proto_goTypes,
		DependencyIndexes: file_service_pc_proto_depIdxs,
		MessageInfos:      file_service_pc_proto_msgTypes,
	}.Build()
	File_service_pc_proto = out.File
	file_service_pc_proto_rawDesc = nil
	file_service_pc_proto_goTypes = nil
	file_service_pc_proto_depIdxs = nil
}
