// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: service_pc.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pc *PC `protobuf:"bytes,1,opt,name=pc,proto3" json:"pc,omitempty"`
}

func (x *CreatePCRequest) Reset() {
	*x = CreatePCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePCRequest) ProtoMessage() {}

func (x *CreatePCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePCRequest.ProtoReflect.Descriptor instead.
func (*CreatePCRequest) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePCRequest) GetPc() *PC {
	if x != nil {
		return x.Pc
	}
	return nil
}

type CreatePCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePCResponse) Reset() {
	*x = CreatePCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePCResponse) ProtoMessage() {}

func (x *CreatePCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePCResponse.ProtoReflect.Descriptor instead.
func (*CreatePCResponse) Descriptor() ([]byte, []int) {
	return file_service_pc_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePCResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_service_pc_proto protoreflect.FileDescriptor

var file_service_pc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x02, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x63, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x50, 0x43, 0x52, 0x02, 0x70, 0x63, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x64, 0x0a,
	0x09, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x08, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x12, 0x17, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x70, 0x63, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_service_pc_proto_rawDescOnce sync.Once
	file_service_pc_proto_rawDescData = file_service_pc_proto_rawDesc
)

func file_service_pc_proto_rawDescGZIP() []byte {
	file_service_pc_proto_rawDescOnce.Do(func() {
		file_service_pc_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_pc_proto_rawDescData)
	})
	return file_service_pc_proto_rawDescData
}

var file_service_pc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_pc_proto_goTypes = []interface{}{
	(*CreatePCRequest)(nil),  // 0: pcbook.CreatePCRequest
	(*CreatePCResponse)(nil), // 1: pcbook.CreatePCResponse
	(*PC)(nil),               // 2: pcbook.PC
}
var file_service_pc_proto_depIdxs = []int32{
	2, // 0: pcbook.CreatePCRequest.pc:type_name -> pcbook.PC
	0, // 1: pcbook.PCService.CreatePC:input_type -> pcbook.CreatePCRequest
	1, // 2: pcbook.PCService.CreatePC:output_type -> pcbook.CreatePCResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_pc_proto_init() }
func file_service_pc_proto_init() {
	if File_service_pc_proto != nil {
		return
	}
	file_pc_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_pc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_pc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_pc_proto_goTypes,
		DependencyIndexes: file_service_pc_proto_depIdxs,
		MessageInfos:      file_service_pc_proto_msgTypes,
	}.Build()
	File_service_pc_proto = out.File
	file_service_pc_proto_rawDesc = nil
	file_service_pc_proto_goTypes = nil
	file_service_pc_proto_depIdxs = nil
}
